services:
  db:
    image: postgres
    ports:
      - 5434:5432
    container_name: test_stripe_db
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test-stripe